CREATE SCHEMA proyectoIntegradorG1;
USE proyectoIntegradorG1;
CREATE TABLE usuarios(
		id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        email VARCHAR(250) NOT NULL UNIQUE,
        contrasenia VARCHAR(500) NOT NULL,
        fecha DATE NOT NULL,
        dni INT NOT NULL,
        foto VARCHAR(300),
        createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        deletedAt  TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP 
);
INSERT INTO usuarios VALUES(
DEFAULT,
'brian@digitalhouse.com',
'1234',
'2005-08-23',
'46956088',
'foto.png',
null,
null,
null
),
(
DEFAULT,
'luis@digitalhouse.com',
'4567',
'2018-10-14',
'23067425',
'foto1.png',
null,
null,
null
),
(
DEFAULT,
'martu@digitalhouse.com',
'hola123',
'2011-02-17',
'12345678',
'foto2.png',
null,
null,
null
),
(
DEFAULT,
'lola@digitalhouse.com',
'lolatequiero',
'2006-01-30',
'47131107',
'foto3.png',
null,
null,
null
),
(
DEFAULT,
'ema@digitalhouse.com',
'emaloveb',
'2005-11-21',
'46915540',
'foto4.png',
null,
null,
null
);
CREATE TABLE productos (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    imagenProducto VARCHAR(255) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    usuario_id INT UNSIGNED,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
INSERT INTO productos VALUES(
DEFAULT,
"img-funda1.jpg",
"Funda Arcoiris",
"Funda de silicona arcoiris, flexible y suave al tacto. Ofrece una excelente protección contra golpes y rayones, mientras le da a tu dispositivo un look moderno y divertido.",
NULL,
NULL,
NULL, 
1
),
(DEFAULT,
"img-funda2.jpg",
"Funda Aurora Pastel",
"Elegante funda de silicona con acabado mate y diseño degradado en tonos pastel. Suave al tacto, flexible y resistente, ideal para proteger tu celular con estilo y personalidad.",
NULL,
NULL,
NULL, 
3
),
(DEFAULT,
"img-funda3.jpg",
"Funda Mármol Rosado Luxe",
"Diseño de mármol rosado con brillos. Elegante, flexible y suave al tacto.",
NULL,
NULL,
NULL,
5
),
(DEFAULT,
"img-funda4.jpg",
"Funda Glam Rosa Mirror",
"Funda con glitter rosa y espejo. Moderna, llamativa y súper elegante.",
NULL,
NULL,
NULL,
2
),
(DEFAULT,
"img-funda5.jpg",
"Funda Glitter Crystal",
"Funda transparente con glitter holográfico. Divertida, brillante y delicada.",
NULL,
NULL,
NULL,
4
),
(DEFAULT,
"img-funda6.jpg",
"Funda Estelar Glitter",
"Funda negra con estrellas brillantes. Original, mágica y súper llamativa.",
NULL,
NULL,
NULL,
1
),
(DEFAULT,
"img-funda7.jpg",
"Funda Green Sparkle",
"Funda verde con estrellas brillantes y mucho glitter!. Original, mágica y súper llamativa.",
NULL,
NULL,
NULL,
5
),
(DEFAULT,
"img-funda8.jpg",
"Funda Butterfly Dream",
"Funda transparente con mariposas violetas. Delicada, fresca y encantadora.",
NULL,
NULL,
NULL,
3
),
(DEFAULT,
"img-funda9.jpg",
"Funda Street-Style",
"Funda transparente con un collage de tickets y distintos simbolos. Delicada, cool y unica.",
NULL,
NULL,
NULL,
2
),
(DEFAULT,
"img-funda10.jpg",
"Funda Love Contrast",
"Funda con corazones rosas y negros. Divertida, moderna y con estilo único.",
NULL,
NULL,
NULL,
1
);